name: makemore
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - numpy
  - sympy
  - matplotlib
  - pandas
  - pyyaml
  - requests
  - tqdm
  - pillow
  - psutil
  - cpuonly  # <-- required for Macs

