name: nanogpt
channels:
  - defaults
  - conda-forge
dependencies:
  - tornado
  - ipykernel
  - nbclassic
  - jupyterlab
  - notebook
  - jupyter_server
  - jupyterlab_server
  - nbconvert
  - ipywidgets
  - python=3.11
  - traitlets
prefix: /home/mrbarinubuntu/miniconda/envs/nanogpt
