name: nanogpt
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - tornado
  - traitlets
  - ipykernel
  - notebook
  - nbconvert
  - jupyterlab
  - nbclassic
  - jupyter_server
  - ipywidgets
  - jupyterlab_server
prefix: /home/mrbarinubuntu/miniconda/envs/nanogpt
