name: makemore
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - cpython=3.11.14
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fqdn=1.5.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.3
  - krb5=1.21.3
  - lark=1.3.1
  - ld_impl_linux-64=2.45
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nbclassic=1.3.3
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandoc=3.8.2.1
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.28.0
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.13.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.3.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - pillow==11.3.0
      - pyparsing==3.2.5
      - torch==2.9.1+cu128
      - torchaudio==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - triton==3.5.1
prefix: /home/mrbarinubuntu/miniconda/envs/makemore
